from pathlib import Path
import json

from fastapi import FastAPI, HTTPException
from shared.schemas.alert_schema import Alert


# ============================================================
# Paths
# ============================================================

PROJECT_ROOT = Path(__file__).resolve().parents[1]

ALERT_FILE = (
    PROJECT_ROOT
    / "module1_road_defect"
    / "data"
    / "alerts"
    / "alerts.jsonl"
)


# ============================================================
# FastAPI application
# ============================================================

app = FastAPI(
    title="Smart Transport Monitoring - Road Defect API",
    version="1.0.0",
    description=(
        "API for accessing validated road-defect alerts "
        "generated by Module 1."
    ),
)


# ============================================================
# Helper functions
# ============================================================

def load_alerts():
    """
    Load all persisted alerts from alerts.jsonl.
    """

    if not ALERT_FILE.exists():
        return []

    alerts = []

    with ALERT_FILE.open(
        "r",
        encoding="utf-8"
    ) as file:

        for line in file:

            line = line.strip()

            if not line:
                continue

            try:
                data = json.loads(line)

                alert = Alert.model_validate(
                    data
                )

                alerts.append(alert)

            except Exception as exc:

                print(
                    "Warning: invalid alert skipped:"
                )

                print(exc)

    return alerts


# ============================================================
# Health endpoint
# ============================================================

@app.get("/health")
def health():

    alerts = load_alerts()

    return {
        "status": "ok",
        "module": "road_defect",
        "version": "1.0",
        "alert_file_exists": ALERT_FILE.exists(),
        "alert_count": len(alerts),
    }


# ============================================================
# Get all alerts
# ============================================================

@app.get("/alerts")
def get_alerts():

    alerts = load_alerts()

    return {
        "count": len(alerts),
        "alerts": [
            alert.model_dump(mode="json")
            for alert in alerts
        ],
    }


# ============================================================
# Get latest alerts
# ============================================================

@app.get("/alerts/latest")
def get_latest_alerts():

    alerts = load_alerts()

    # Return latest 10 alerts.
    latest = alerts[-10:]

    # Reverse so newest appears first.
    latest.reverse()

    return {
        "count": len(latest),
        "alerts": [
            alert.model_dump(mode="json")
            for alert in latest
        ],
    }


# ============================================================
# Get a specific alert
# ============================================================

@app.get("/alerts/{alert_id}")
def get_alert(alert_id: str):

    alerts = load_alerts()

    for alert in alerts:

        if alert.alert_id == alert_id:

            return alert.model_dump(
                mode="json"
            )

    raise HTTPException(
        status_code=404,
        detail=(
            f"Alert '{alert_id}' "
            f"not found."
        ),
    )


# ============================================================
# Local test
# ============================================================

if __name__ == "__main__":

    print("=" * 60)
    print("ROAD DEFECT API")
    print("=" * 60)

    print(
        f"\nAlert file:"
    )

    print(
        ALERT_FILE
    )

    print(
        f"\nAlert file exists:"
        f" {ALERT_FILE.exists()}"
    )

    alerts = load_alerts()

    print(
        f"Alerts loaded:"
        f" {len(alerts)}"
    )

    print(
        "\nStart the API with:"
    )

    print(
        "python -m uvicorn "
        "module1_road_defect.api:app "
        "--host 127.0.0.1 "
        "--port 8000"
    )